import { computed, type ComputedRef, type Ref } from 'vue'

const zh = {
  title: 'Prompt 异步审计',
  description: '下游响应完成后异步扫描，仅保留哈希、脱敏预览和审计结果。',
  configuration: '配置',
  events: '事件',
  refresh: '刷新',
  save: '保存配置',
  saving: '保存中',
  enabled: '已启用',
  disabled: '已关闭',
  asyncMode: '异步审计',
  offMode: '关闭',
  asyncExplanation: '审计任务仅在请求处理完成后入队，不在首 Token 前访问数据库、Redis 或 Guard 端点。',
  lastUpdated: '配置更新',
  runtime: '运行状态',
  queue: '队列',
  processed: '已处理',
  enqueued: '已入队',
  dropped: '已丢弃',
  failed: '失败',
  workers: 'Worker',
  runtimeUnavailable: '暂无运行数据',
  generalSettings: '执行与保留',
  auditSwitch: '启用 Prompt 异步审计',
  workerCount: 'Worker 数量',
  workerHint: '1-16',
  queueCapacity: '队列容量',
  queueHint: '1-100000',
  retentionDays: '事件保留天数',
  retentionHint: '1-90 天',
  storePass: '保留通过事件',
  storePassHint: '关闭后仅保留标记、高风险和扫描不可用事件。',
  groupScope: '分组范围',
  allGroups: '所有分组',
  selectedGroups: '指定分组',
  noGroups: '没有可用分组',
  scanners: '检测类别',
  guardPool: 'OpenAI-compatible Guard 端点池',
  guardPoolHint: '按顺序尝试已启用端点；保存时 token 留空会保留现有值。',
  addEndpoint: '添加端点',
  emptyEndpoints: '尚未配置 Guard 端点。',
  endpoint: '端点',
  endpointEnabled: '参与扫描',
  endpointId: '端点 ID',
  endpointName: '名称',
  baseUrl: 'Base URL',
  model: '模型',
  timeout: '超时 (ms)',
  token: 'Bearer Token',
  tokenConfigured: '已保存 token',
  tokenMissing: '未配置 token',
  tokenKeepPlaceholder: '留空保留现有 token',
  tokenNewPlaceholder: '可选，仅在端点需要认证时填写',
  clearToken: '保存时清除已有 token',
  privateEndpoint: '允许访问私网端点',
  privateWarning: '私网访问会放宽网络边界，必须逐项配置 CIDR 白名单。元数据、链路本地、多播和重定向仍会被拒绝。',
  cidrs: 'CIDR 白名单',
  cidrsPlaceholder: '每行一项，例如 10.20.0.0/16',
  probe: '探测',
  probing: '探测中',
  remove: '删除端点',
  healthy: '连接正常',
  unhealthy: '连接失败',
  probeTokenHint: '探测会在服务端安全复用已保存 token，不会回显凭据。',
  latency: '延迟',
  filters: '事件筛选',
  decision: '决策',
  allDecisions: '全部决策',
  risk: '风险',
  allRisks: '全部风险',
  group: '分组',
  allGroupsFilter: '全部分组',
  userId: '用户 ID',
  search: '搜索',
  searchPlaceholder: '请求 ID、用户邮箱或 Prompt 哈希',
  apply: '查询',
  reset: '重置',
  deleteFiltered: '删除筛选结果',
  deleteSelected: '删除已选',
  selectedCount: '已选 {count} 项',
  time: '时间',
  identity: '用户 / API Key',
  route: '请求',
  preview: '脱敏预览',
  scanner: '扫描器',
  actions: '操作',
  details: '详情',
  delete: '删除',
  noEvents: '暂无审计事件。',
  loading: '加载中',
  requestId: '请求 ID',
  promptHash: 'Prompt 哈希',
  promptLength: 'Prompt 字符数',
  messageCount: '消息数',
  stage: '阶段',
  providerProtocol: '平台 / 协议',
  categories: '类别',
  scannerBackend: '扫描后端',
  guardEndpoint: 'Guard 端点 ID',
  errorCode: '错误码',
  noPromptNotice: '详情仅包含脱敏预览和哈希，不提供完整 Prompt。',
  close: '关闭',
  cancel: '取消',
  confirmDelete: '确认删除',
  deleteOneHint: '将永久删除该审计事件。',
  deleteBatchHint: '将永久删除 {count} 个已选事件。',
  previewingDelete: '正在生成删除预览',
  deletePreviewTitle: '删除筛选结果',
  deletePreviewHint: '将删除最多到当前预览快照的 {count} 个事件，新产生的事件不会被误删。',
  previewExpires: '确认有效期至 {time}',
  nothingToDelete: '当前筛选条件下没有可删除事件。',
  configSaved: '审计配置已保存',
  deletedCount: '已删除 {count} 个审计事件',
  loadFailed: '无法加载 Prompt 审计数据',
  saveFailed: '无法保存 Prompt 审计配置',
  probeFailed: '无法完成 Guard 端点探测',
  deleteFailed: '无法删除审计事件',
  detailFailed: '无法加载审计事件详情',
  invalidForm: '请检查配置中的必填项和取值范围',
  pass: '通过',
  flag: '标记',
  critical: '严重',
  unavailable: '不可用',
  low: '低',
  medium: '中',
  high: '高',
  unknown: '未知',
  scannerLabels: {
    violent: '暴力',
    non_violent_illegal_acts: '非暴力违法行为',
    sexual_content_or_sexual_acts: '性内容或性行为',
    pii: '个人识别信息',
    suicide_and_self_harm: '自杀与自伤',
    unethical_acts: '不道德行为',
    politically_sensitive_topics: '政治敏感话题',
    copyright_violation: '版权侵犯',
    jailbreak: '越狱 / Prompt 注入'
  }
}

const en: typeof zh = {
  ...zh,
  title: 'Prompt Audit',
  description: 'Asynchronous post-response scanning that retains only hashes, redacted previews, and audit results.',
  configuration: 'Configuration', events: 'Events', refresh: 'Refresh', save: 'Save configuration', saving: 'Saving', enabled: 'Enabled', disabled: 'Disabled', asyncMode: 'Async audit', offMode: 'Off',
  asyncExplanation: 'Audit tasks enter the queue only after request handling completes. No database, Redis, or Guard call is added before the first token.',
  lastUpdated: 'Configuration updated', runtime: 'Runtime', queue: 'Queue', processed: 'Processed', enqueued: 'Enqueued', dropped: 'Dropped', failed: 'Failed', workers: 'Workers', runtimeUnavailable: 'Runtime data unavailable',
  generalSettings: 'Execution and retention', auditSwitch: 'Enable asynchronous Prompt Audit', workerCount: 'Worker count', workerHint: '1-16', queueCapacity: 'Queue capacity', queueHint: '1-100000', retentionDays: 'Event retention', retentionHint: '1-90 days',
  storePass: 'Store passed events', storePassHint: 'When disabled, only flagged, critical, and unavailable scans are retained.', groupScope: 'Group scope', allGroups: 'All groups', selectedGroups: 'Selected groups', noGroups: 'No groups available', scanners: 'Detection categories',
  guardPool: 'OpenAI-compatible Guard endpoint pool', guardPoolHint: 'Enabled endpoints are tried in order. An empty token preserves the saved token when configuration is saved.', addEndpoint: 'Add endpoint', emptyEndpoints: 'No Guard endpoints configured.', endpoint: 'Endpoint', endpointEnabled: 'Use for scanning', endpointId: 'Endpoint ID', endpointName: 'Name', baseUrl: 'Base URL', model: 'Model', timeout: 'Timeout (ms)', token: 'Bearer token', tokenConfigured: 'Token saved', tokenMissing: 'No token', tokenKeepPlaceholder: 'Leave empty to preserve the saved token', tokenNewPlaceholder: 'Optional; enter only if this endpoint requires authentication', clearToken: 'Clear the saved token on save',
  privateEndpoint: 'Allow a private network endpoint', privateWarning: 'Private access broadens the network boundary and requires an explicit CIDR allowlist. Metadata, link-local, multicast, and redirected destinations remain blocked.', cidrs: 'CIDR allowlist', cidrsPlaceholder: 'One per line, for example 10.20.0.0/16', probe: 'Probe', probing: 'Probing', remove: 'Remove endpoint', healthy: 'Connection healthy', unhealthy: 'Connection failed', probeTokenHint: 'The server securely reuses the saved token without returning the credential.', latency: 'Latency',
  filters: 'Event filters', decision: 'Decision', allDecisions: 'All decisions', risk: 'Risk', allRisks: 'All risks', group: 'Group', allGroupsFilter: 'All groups', userId: 'User ID', search: 'Search', searchPlaceholder: 'Request ID, user email, or Prompt hash', apply: 'Search', reset: 'Reset', deleteFiltered: 'Delete filtered events', deleteSelected: 'Delete selected', selectedCount: '{count} selected', time: 'Time', identity: 'User / API key', route: 'Request', preview: 'Redacted preview', scanner: 'Scanner', actions: 'Actions', details: 'Details', delete: 'Delete', noEvents: 'No audit events.', loading: 'Loading',
  requestId: 'Request ID', promptHash: 'Prompt hash', promptLength: 'Prompt characters', messageCount: 'Messages', stage: 'Stage', providerProtocol: 'Platform / protocol', categories: 'Categories', scannerBackend: 'Scanner backend', guardEndpoint: 'Guard endpoint ID', errorCode: 'Error code', noPromptNotice: 'Details contain only a redacted preview and hash. The full prompt is never provided.', close: 'Close', cancel: 'Cancel', confirmDelete: 'Confirm deletion', deleteOneHint: 'This audit event will be permanently deleted.', deleteBatchHint: '{count} selected audit events will be permanently deleted.', previewingDelete: 'Preparing deletion preview', deletePreviewTitle: 'Delete filtered events', deletePreviewHint: 'Up to {count} events in this preview snapshot will be deleted. New events will not be included.', previewExpires: 'Confirmation expires at {time}', nothingToDelete: 'No events match the current filters.', configSaved: 'Prompt Audit configuration saved', deletedCount: 'Deleted {count} audit events', loadFailed: 'Unable to load Prompt Audit data', saveFailed: 'Unable to save Prompt Audit configuration', probeFailed: 'Unable to probe the Guard endpoint', deleteFailed: 'Unable to delete audit events', detailFailed: 'Unable to load audit event details', invalidForm: 'Check required fields and value ranges in the configuration.',
  pass: 'Pass', flag: 'Flag', critical: 'Critical', unavailable: 'Unavailable', low: 'Low', medium: 'Medium', high: 'High', unknown: 'Unknown',
  scannerLabels: {
    violent: 'Violence', non_violent_illegal_acts: 'Non-violent illegal acts', sexual_content_or_sexual_acts: 'Sexual content or acts', pii: 'Personal identifying information', suicide_and_self_harm: 'Suicide and self-harm', unethical_acts: 'Unethical acts', politically_sensitive_topics: 'Politically sensitive topics', copyright_violation: 'Copyright violation', jailbreak: 'Jailbreak / prompt injection'
  }
}

export type PromptAuditCopy = typeof zh

export function usePromptAuditCopy(locale: Ref<string>): ComputedRef<PromptAuditCopy> {
  return computed(() => locale.value.toLowerCase().startsWith('zh') ? zh : en)
}
